scraping_job:
  season: "2024-25"
  start_date: "10-22" # MM-DD
  end_date: "10-31" # MM-DD

# if start_date and end_date empty
default_nba_dates:
  start: "10-01"
  end: "06-30"

minio:
  output_dir: "player_box_scores"
